export const RAPHAEL_PROFILE_KEY = "raphael-v1";

export const RAPHAEL_PROFILE = {
  displayName: "Raphael",
  locale: "pt-BR",
  currency: "BRL",
  timezone: "America/Sao_Paulo",
  planningHorizon: "2026-12-31",
  tone: "objetivo, humano e firme",
  riskPreference: "baixo risco e alta liquidez",
  operatingBufferCents: 500_000,
  monthlyVariableBudgetCents: 300_000,
  emergencyFundReferenceCents: 818_000,
  emergencyFundTargetMonths: 6,
  projectTaxBasisPoints: 1500,
  projectCostBasisPoints: 1000,
  projectGoalBasisPoints: 7500,
  carMonthlyLimitCents: 500_000,
  carInstallmentLimitCents: 300_000,
  quietHoursStart: "21:00",
  quietHoursEnd: "08:00",
} as const;

export const RAPHAEL_ACCOUNTS = [
  {
    seedKey: "account-pf",
    name: "Conta PF",
    ownerType: "personal",
    accountType: "checking",
    includeInOperatingCash: true,
    protected: false,
  },
  {
    seedKey: "account-pj",
    name: "Conta PJ",
    ownerType: "business",
    accountType: "checking",
    includeInOperatingCash: true,
    protected: false,
  },
  {
    seedKey: "account-reserve",
    name: "Reserva de emergência",
    ownerType: "personal",
    accountType: "reserve",
    includeInOperatingCash: false,
    protected: true,
  },
  {
    seedKey: "account-car-fund",
    name: "Fundo do carro",
    ownerType: "personal",
    accountType: "savings",
    includeInOperatingCash: false,
    protected: true,
  },
] as const;

type CategorySeed = {
  key: string;
  name: string;
  group: string;
  ownerType: "personal" | "business" | "both";
  essential: boolean;
};

function categories(
  group: string,
  ownerType: CategorySeed["ownerType"],
  essential: boolean,
  entries: Array<[string, string]>
): CategorySeed[] {
  return entries.map(([key, name]) => ({
    key,
    name,
    group,
    ownerType,
    essential,
  }));
}

export const RAPHAEL_CATEGORIES: CategorySeed[] = [
  ...categories("personal_fixed", "personal", true, [
    ["aluguel", "Aluguel"],
    ["condominio", "Condomínio"],
    ["energia", "Energia"],
    ["agua", "Água"],
    ["gas", "Gás"],
    ["internet_telefone", "Internet e telefone"],
    ["academia", "Academia"],
    ["clube", "Clube"],
    ["apoio_rafaela", "Apoio à Rafaela"],
  ]),
  ...categories("personal_variable", "personal", false, [
    ["mercado", "Mercado"],
    ["alimentacao_fora", "Alimentação fora"],
    ["delivery", "Delivery"],
    ["farmacia_saude", "Farmácia e saúde"],
    ["transporte", "Transporte"],
    ["combustivel", "Combustível"],
    ["lazer", "Lazer"],
    ["roupas", "Roupas"],
    ["criancas", "Crianças"],
    ["casa", "Casa"],
    ["beleza", "Beleza"],
    ["doacoes", "Doações"],
    ["outros", "Outros"],
  ]),
  ...categories("business", "business", false, [
    ["receita_cliente", "Receita de cliente"],
    ["ferramentas", "Ferramentas"],
    ["hospedagem", "Hospedagem"],
    ["anuncios", "Anúncios"],
    ["freelancers", "Freelancers"],
    ["impostos", "Impostos"],
    ["taxas", "Taxas"],
    ["equipamentos", "Equipamentos"],
    ["retirada_socio", "Retirada de sócio"],
    ["despesa_pessoal_na_pj", "Despesa pessoal na PJ"],
  ]),
  ...categories("financial", "both", true, [
    ["reserva_emergencia", "Reserva de emergência"],
    ["fundo_carro", "Fundo do carro"],
    ["divida", "Dívida"],
    ["juros", "Juros"],
    ["transferencia_interna", "Transferência interna"],
    ["valor_a_classificar", "Valor a classificar"],
  ]),
];

export const RAPHAEL_RECURRING_CASHFLOWS = [
  {
    seedKey: "income-main-day-30",
    type: "income",
    ownerType: "business",
    name: "Recebimento principal",
    amountCents: 2_000_000,
    recurrenceRule: "FREQ=MONTHLY;BYMONTHDAY=30",
    status: "expected",
    estimated: false,
    needsConfirmation: false,
    categoryKey: "receita_cliente",
    accountSeedKey: "account-pj",
  },
  {
    seedKey: "income-complement-fifth-business-day",
    type: "income",
    ownerType: "business",
    name: "Complemento mensal",
    amountCents: 600_000,
    recurrenceRule: "FREQ=MONTHLY;BYBUSINESSDAY=5",
    status: "expected",
    estimated: false,
    needsConfirmation: false,
    categoryKey: "receita_cliente",
    accountSeedKey: "account-pj",
  },
  {
    seedKey: "one-off-computer-sale",
    type: "income",
    ownerType: "personal",
    name: "Venda do computador",
    amountCents: 500_000,
    recurrenceRule: "ONCE",
    status: "expected",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "outros",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "one-off-2500-receivable",
    type: "income",
    ownerType: "personal",
    name: "Valor a receber até o fim do mês",
    amountCents: 250_000,
    recurrenceRule: "ONCE",
    status: "expected",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "outros",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-rent",
    type: "expense",
    ownerType: "personal",
    name: "Aluguel",
    amountCents: 330_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "aluguel",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-condominium",
    type: "expense",
    ownerType: "personal",
    name: "Condomínio",
    amountCents: 60_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "condominio",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-gas",
    type: "expense",
    ownerType: "personal",
    name: "Gás",
    amountCents: 33_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "gas",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-internet",
    type: "expense",
    ownerType: "personal",
    name: "Claro e internet",
    amountCents: 35_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "internet_telefone",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-energy",
    type: "expense",
    ownerType: "personal",
    name: "Energia elétrica",
    amountCents: 35_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "energia",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-water",
    type: "expense",
    ownerType: "personal",
    name: "Água",
    amountCents: 15_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "agua",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-fuel",
    type: "expense",
    ownerType: "personal",
    name: "Gasolina",
    amountCents: 80_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "combustivel",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-market",
    type: "expense",
    ownerType: "personal",
    name: "Mercado e alimentação da casa",
    amountCents: 140_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: false,
    needsConfirmation: false,
    categoryKey: "mercado",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-rafaela",
    type: "expense",
    ownerType: "personal",
    name: "Valor mensal para Rafaela",
    amountCents: 60_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: false,
    needsConfirmation: false,
    categoryKey: "apoio_rafaela",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-club",
    type: "expense",
    ownerType: "personal",
    name: "Clube",
    amountCents: 10_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: false,
    needsConfirmation: false,
    categoryKey: "clube",
    accountSeedKey: "account-pf",
  },
  {
    seedKey: "expense-gym",
    type: "expense",
    ownerType: "personal",
    name: "Academia",
    amountCents: 20_000,
    recurrenceRule: "FREQ=MONTHLY",
    status: "planned",
    estimated: true,
    needsConfirmation: true,
    categoryKey: "academia",
    accountSeedKey: "account-pf",
  },
] as const;

export const RAPHAEL_GOALS = [
  {
    seedKey: "goal-operating-buffer",
    name: "Colchão operacional",
    goalType: "operating_buffer",
    targetCents: 500_000,
    priority: "critical",
    protected: true,
  },
  {
    seedKey: "goal-emergency-min-current",
    name: "Reserva mínima atual",
    goalType: "emergency_fund",
    targetCents: 4_908_000,
    priority: "critical",
    protected: true,
  },
  {
    seedKey: "goal-emergency-ideal-current",
    name: "Reserva ideal atual",
    goalType: "emergency_fund",
    targetCents: 6_708_000,
    priority: "essential",
    protected: true,
  },
  {
    seedKey: "goal-emergency-min-post-car",
    name: "Reserva mínima pós-carro",
    goalType: "emergency_fund_post_car",
    targetCents: 7_428_000,
    priority: "critical",
    protected: true,
  },
  {
    seedKey: "goal-emergency-ideal-post-car",
    name: "Reserva ideal pós-carro",
    goalType: "emergency_fund_post_car",
    targetCents: 9_228_000,
    priority: "important",
    protected: true,
  },
  {
    seedKey: "goal-family-purchases",
    name: "Compras da família e da casa",
    goalType: "purchase_plan",
    targetCents: 2_609_750,
    priority: "essential",
    protected: false,
  },
  {
    seedKey: "goal-car-fund",
    name: "Entrada e custos iniciais do carro",
    goalType: "car_fund",
    targetCents: 0,
    priority: "important",
    protected: true,
    notes:
      "Meta bloqueada até informar valor do veículo, entrada, prazo e CET.",
  },
] as const;

type GoalItemSeed = {
  seedKey: string;
  personOrGroup: string;
  name: string;
  estimatedCostCents: number;
  priority: "essential" | "important" | "optional";
  needsConfirmation?: boolean;
  notes?: string;
};

function item(
  personOrGroup: string,
  key: string,
  name: string,
  estimatedCostCents: number,
  priority: GoalItemSeed["priority"],
  extra: Pick<GoalItemSeed, "needsConfirmation" | "notes"> = {}
): GoalItemSeed {
  return {
    seedKey: `purchase-${personOrGroup.toLowerCase()}-${key}`,
    personOrGroup,
    name,
    estimatedCostCents,
    priority,
    ...extra,
  };
}

export const RAPHAEL_GOAL_ITEMS: GoalItemSeed[] = [
  item("Mavi", "roupas", "Roupas", 50_000, "essential"),
  item("Mavi", "fraldas", "Fraldas", 50_000, "essential", {
    needsConfirmation: true,
    notes: "Confirmar se é compra única ou gasto mensal.",
  }),
  item("Mavi", "acessorios", "Acessórios", 50_000, "essential"),
  item("Rafaela", "pijamas", "2 pijamas", 24_000, "essential"),
  item("Rafaela", "celular", "Celular", 450_000, "optional"),
  item("Rafaela", "tops", "2 tops", 10_000, "essential"),
  item("Rafaela", "sutias", "3 sutiãs", 18_000, "essential"),
  item(
    "Rafaela",
    "pos-parto",
    "Fralda ou roupa íntima pós-parto",
    8_000,
    "essential"
  ),
  item(
    "Rafaela",
    "absorventes-seios",
    "Absorventes de seios",
    7_500,
    "essential"
  ),
  item("Rafaela", "roupas", "Roupas", 130_000, "important"),
  item("Rafaela", "tape", "Tape", 20_000, "essential"),
  item("Rafaela", "oleo", "Óleo", 10_000, "essential"),
  item("Rafaela", "creme-estrias", "Creme para estrias", 10_000, "essential"),
  item("Rafaela", "maquiagem", "Blush, primer e corretivo", 16_000, "optional"),
  item("Rafaela", "corte-cabelo", "Corte de cabelo", 15_000, "optional"),
  item("Rafaela", "pintura-cabelo", "Pintura do cabelo", 100_000, "optional"),
  item("Rafaela", "coletor-leite", "Coletor de leite", 6_000, "essential"),
  item(
    "Rafaela",
    "maquina-leite",
    "Máquina elétrica de tirar leite",
    25_000,
    "essential"
  ),
  item("Elisa", "roupa-piscina", "Roupa de piscina", 10_000, "important"),
  item("Elisa", "papete", "Papete para escola", 10_000, "important"),
  item("Elisa", "tenis", "Tênis para sair", 15_000, "important"),
  item("Elisa", "shorts", "6 shorts", 30_000, "important"),
  item("Elisa", "camisetas", "7 camisetas", 28_000, "important"),
  item("Elisa", "calcinhas", "7 calcinhas", 13_000, "important"),
  item("Elisa", "pijamas", "2 pijamas", 12_000, "important"),
  item("Elisa", "calcas", "3 calças", 27_000, "important"),
  item("Gael", "roupa-piscina", "Roupa de piscina", 7_000, "important"),
  item("Gael", "papete", "Papete para escola", 10_000, "important"),
  item(
    "Gael",
    "camisetas-longas",
    "3 camisetas de manga longa",
    12_000,
    "important"
  ),
  item("Gael", "camisetas-sair", "3 camisetas para sair", 15_000, "important"),
  item("Gael", "calcas-sair", "3 calças para sair", 27_000, "important"),
  item("Gael", "cuecas", "7 cuecas", 10_000, "important"),
  item("Gael", "pijamas", "2 pijamas", 12_000, "important"),
  item("Casa", "comoda", "Cômoda", 180_000, "important"),
  item("Casa", "cama-criancas", "Cama das crianças", 150_000, "essential"),
  item("Casa", "sofa", "Sofá", 350_000, "optional"),
  item("Casa", "maquina-lavar", "Máquina de lavar", 350_000, "essential"),
  item("Casa", "pratos", "Pratos", 40_000, "essential"),
  item("Casa", "copos", "Copos", 5_000, "essential"),
  item("Casa", "panelas", "Panelas", 60_000, "essential"),
];

export const RAPHAEL_INITIAL_TASKS = [
  [
    "confirm-computer-sale",
    "Confirmar valor e conclusão da venda do computador",
    "critical",
  ],
  ["confirm-2500-date", "Confirmar data dos R$ 2.500 a receber", "high"],
  ["pay-asaas", "Cadastrar vencimento e quitar Asaas", "critical"],
  ["confirm-fixed-costs", "Confirmar contas fixas estimadas", "high"],
  ["create-reserve-account", "Criar conta separada de reserva", "high"],
  [
    "classify-porto-seguro",
    "Classificar R$ 4.289,07 de Porto Seguro",
    "medium",
  ],
  [
    "confirm-mavi-diapers",
    "Confirmar se fraldas da Mavi são recorrentes",
    "medium",
  ],
  [
    "confirm-replacement-computer",
    "Confirmar se há equipamento substituto após vender o computador",
    "high",
  ],
  [
    "register-project-target",
    "Registrar meta mensal de R$ 10.000 em projetos",
    "high",
  ],
] as const;

export const RAPHAEL_MERCHANT_RULES = [
  ["GNI", "aluguel", "personal"],
  ["JAC NEGÓCIOS", "aluguel", "personal"],
  ["CLARO", "internet_telefone", "personal"],
  ["COMPANHIA DE GÁS", "gas", "personal"],
  ["SAAE", "agua", "personal"],
  ["CONTA DE ÁGUA", "agua", "personal"],
  ["POSTO", "combustivel", "personal"],
  ["AUTO POSTO", "combustivel", "personal"],
  ["ASSAÍ", "mercado", "personal"],
  ["CARREFOUR", "mercado", "personal"],
  ["TAUSTE", "mercado", "personal"],
  ["WMB", "mercado", "personal"],
  ["HORTIFRUT", "mercado", "personal"],
  ["IFOOD", "delivery", "personal"],
  ["RESTAURANTE", "alimentacao_fora", "personal"],
  ["CAFÉ", "alimentacao_fora", "personal"],
  ["LANCHONETE", "alimentacao_fora", "personal"],
  ["PIZZARIA", "alimentacao_fora", "personal"],
  ["AÇAÍ", "alimentacao_fora", "personal"],
  ["DROGARIA", "farmacia_saude", "personal"],
  ["FARMA", "farmacia_saude", "personal"],
  ["RAIA", "farmacia_saude", "personal"],
  ["PAGUE MENOS", "farmacia_saude", "personal"],
  ["99 TECNOLOGIA", "transporte", "personal"],
  ["PORTO SEGURO", "valor_a_classificar", "both"],
  ["RECEITA FEDERAL", "impostos", "business"],
  ["IGREJA", "doacoes", "personal"],
] as const;
